---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: de-e21-kalo-e78hxkr6u-0-0-0-source
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/dzsicloudedge/manifest

