---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-e01-ping-dkzgwlino-0-0-0-hr
  namespace: default
spec:
  chart:
    spec:
      chart: ./de-e01-ping-dkzgwlino-0-0-0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: de-e01-ping-dkzgwlino-0-0-0-source
  interval: 5m0s
  releaseName: de-e01-ping-dkzgwlino-0-0-0
  values:
    global:
      namespace: default
      nsId: 4ef04db6-a189-4b49-aaad-2415bcd661c2
    internalVldInterface: ens2f0
    ping:
      image:
        imagePullSecrets: []
        pullPolicy: IfNotPresent
        repository: artifactory.riftio.com/docker/rw.ping
        tag: "2004"
      metrics:
        annotations:
          path: /api/v1/ping/metrics
          port: 18888
          scrape: true
        enabled: true
      replicaCount: 1
      serviceType: NodePort
    pong:
      image:
        imagePullSecrets: []
        pullPolicy: IfNotPresent
        repository: artifactory.riftio.com/docker/rw.pong
        tag: "2005"
      metrics:
        annotations:
          path: /api/v1/pong/metrics
          port: 18889
          scrape: true
        enabled: true
      replicaCount: 1
      serviceType: LoadBalancer

