---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: de-e02-ping-hpgekwltx-0-0-0-source
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/dzsicloudedge/manifest

