---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: de-e49-kalo-chcp34b0f-0-0-0-source
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/dzsicloudedge/manifest

